import type { ScorePayload } from "../../scoring.types";

export interface NormalizedAutoAnswers {
  budgetRange: ScorePayload["answers"]["budgetRange"] | null;
  budgetTier: number | null;
  budgetMidpointLakh: number | null;
  primaryPreference: ScorePayload["answers"]["primaryPreference"] | null;
  purchaseTimeline: ScorePayload["answers"]["purchaseTimeline"] | null;
  timelineUrgency: number;
  financePreference: ScorePayload["answers"]["financePreference"] | null;
  brandCount: number;
  brandsComparing: string[];
  brandSegments: string[];
  downPaymentBand: ScorePayload["answers"]["downPaymentBand"] | null;
  salaryBand: ScorePayload["answers"]["salaryBand"] | null;
  salaryTier: number | null;
  salaryMidpointLakh: number | null;
  bodyStyle: ScorePayload["answers"]["bodyStyle"] | null;
  fuelType: ScorePayload["answers"]["fuelType"] | null;
  usagePattern: ScorePayload["answers"]["usagePattern"] | null;
  monthlyKmBand: ScorePayload["answers"]["monthlyKmBand"] | null;
  purchaseReason: ScorePayload["answers"]["purchaseReason"] | null;
  currentVehicleAgeBand: ScorePayload["answers"]["currentVehicleAgeBand"] | null;
  decisionMaker: ScorePayload["answers"]["decisionMaker"] | null;
  variantClarity: ScorePayload["answers"]["variantClarity"] | null;
  testDriveReadiness: ScorePayload["answers"]["testDriveReadiness"] | null;
  monthlyEmiComfortBand: ScorePayload["answers"]["monthlyEmiComfortBand"] | null;
  tradeInAvailable: boolean | null;
  answeredQuestionCount: number;
  answeredCoreQuestionCount: number;
  answeredOptionalQuestionCount: number;
  fundingAnswerCount: number;
  demandSignalCount: number;
  declarationAnswerCount: number;
  declarationCompletionRatePercent: number;
  declaredCompletionRatePercent: number | null;
  effectiveCompletionRatePercent: number;
  completionRateSource: "declared" | "derived_from_declaration";
  stepTimingCoverageCount: number;
  stepTimingTotalSeconds: number;
  averageStepSeconds: number | null;
  maxStepSeconds: number | null;
  engagementPace: "measured" | "rushed" | "slow" | "unknown";
  sessionFocus: "strong" | "mixed" | "weak" | "unknown";
  frictionLevel: "low" | "moderate" | "high";
  demandClarity: "high" | "medium" | "low";
  demandStage: "transaction_ready" | "active_eval" | "researching";
  salaryBudgetAlignment: "strong" | "moderate" | "weak" | "unknown";
  budgetBrandAlignment: "strong" | "stretch" | "mismatch" | "unknown";
  budgetEmiAlignment: "strong" | "moderate" | "weak" | "unknown";
  preferenceBrandAlignment: "strong" | "moderate" | "weak" | "unknown";
  bodyStyleUsageAlignment: "strong" | "moderate" | "weak" | "unknown";
  fuelUsageAlignment: "strong" | "moderate" | "weak" | "unknown";
  fundingReadiness: "strong" | "moderate" | "weak" | "unknown";
  replacementPressure: "high" | "medium" | "low";
  decisionAuthority: "strong" | "shared" | "external" | "unknown";
  comparisonBreadth: "none" | "focused" | "broad";
}
